### ISSUE TITLE
[토론][채팅] 채팅방 구독 정책 및 알림 기능에 대해서

### ISSUE THREAD

**Issue by hyun98** [jojaeng2/2joryu#24]
# 의제
카톡, 페메와 같이 채팅방별 메시지 알림 및 미리보기와 같은 기능을 위해서 구독(이하 sub) 기준을 정한다.

[채팅 기획서](https://github.com/jojaeng2/3hyun-Ktwitter/wiki/%EA%B8%B0%ED%9A%8D-%E2%80%90-%EC%B1%84%ED%8C%85)

<br>

### 특징
1.  사용하지 않는 sub(채팅방)에 대해서도 계속 sub를 관리하게 되므로 리소스 낭비
2.  모든 유저가 로그인 한 상태인 경우에 N*N 개의 sub 생성
3.  서버측에선 별도의 추가 로직이 필요하지 않음

### 특징
1.  모든 유저가 로그인 한 상태인 경우 N개의 sub 기본 생성
2.  각 유저가 모든 채팅방을 활성화 한 경우 N*N + N 개의 sub 생성
3.  그룹 채팅방에 메시지 발행 시 해당 채팅방의 모든 유저들(채널)에 대해서 메시지 발행
4.  유저별 sub은 추후 피드알림, 친구요청알림 등 알림 기능에 사용될 수 있음
    - 알림 기능 추가 시 클라이언트의 소켓 메시지 파싱 관련 복잡도가 높아질 수 있음

**Comment by hyun98** [comment]
각 방법론 별 특징 생각나는거 있으시면 적어주십숑
추가적인 방법이 있다면 의견주시면 감사하겠습니다~

나중에 특징들 종합해서 비교한담에 결정해요~

**Comment by jojaeng2** [comment]
### 1. 로그인 및 앱 입장 시 유저의 모든 채팅방에 대해서 sub
#### 장점
1. 구현 쉬움
2. 좀더 완성도 있는 것처럼 보이는 애플리케이션 만들 수 있음
#### 단점
1. 스레드 낭비
- 클라이언트와 소켓 연결을 수행하면 서버는 1개의 스레드를 사용합니다. (제가 알기론, 확실 x 테스트 진행 필요)
- spring의 thread pool의 최댓값(default)는 200개입니다. [참고](https://velog.io/@sihyung92/how-does-springboot-handle-multiple-requests)
- 따라서 이론상 한대의 springboot server(별도의 설정을 안했다고 가정)로 200개의 client 요청만 수행할 수 있습니다.

2. 굳이 입장안한 채팅방도 구독을 해야하는가?
입장하지 않은 채팅방도 구독을 하는 것이 조금 와닿지 않네요. 사실 클라 측에서는 메시지가 오지 않은 것처럼 보이게 구현할 수는 있겠지만 크롬 네트워크 탭에 들어가면 들어가지 않은 채팅방의 메시지를 결국 다 볼 수 있다는건데, 클라이언트-서버 두 곳 모두 이 부분 대처가 불가능 합니다.

### 2. 로그인 및 앱 입장 시 하나의 sub, 채팅방에 입장 시 방 별 추가 sub
#### 장점
1. 서버 측에서는 구현하기 쉬움
2. 별도로 알람 기능이 필요하지 않음
3. 이후 실시간 관련 기능 추가 쉬움

#### 단점
1. 너무 많은 topic 
1개의 메시지가 전송되면 N+1개의  topic에 메시지 전송해야 함. -> 성능적으로 실시간성이 떨어지지 않을까? 
redis을 MQ로 쓸때 publish하는 연산은 시간 복잡도가 O(N)이 소요됩니다. (N은 구독자의 수)
따라서 topic이 M개일때, O(N*M+1)이 소요되겠네요

2. 불필요한 소켓 통신 수행
클라이언트의 입장에서 생각해보면, 현재 화면에 보여주는 기능이 아니더라도, 다른 소켓 메시지들을 전부 받습니다. (ex: 피드 화면을 띄우는데 굳이 채팅 메시지도 받는 상황, 실제로 화면에 보여주진 않음)
3. 스레드 낭비
1번 방안과 같은 문제
4. topic이 죽어버리면, 모든 기능이 죽어버립니다.
채팅 메시지가 너무 많아서 토픽이 죽었다고 가정했을때, 피드 알림, 친구 요청 기능들이 전부 고장납니다.


#### 의견
계속 생각해봤는데, 채팅방(topic, channel)을 구독하는 순간은 채팅방에 입장했을때가 맞는 것 같습니다. 그리고 카톡처럼 지금 온 메시지를 보여주는 기능은 알림 기능(SSE, FCM 등)으로 구현하는건 어떨까요?
여러 기능을 하나의 로직에 다 묶어버리는건 너무 위험한 것 같습니다.

**Comment by hyun98** [comment]
저도 채팅방 입장 시 구독하는게 좋다고 생각합니다.
SSE, FCM은 몰랐는데...👍 
찾아보니까 채팅 알림은 SSE 방식이 좋아보이고, 친구 요청같은 메시지는 FCM이 좋아보이네요.  아무래도 알림은 서버->클라이언트 단방향이다보니 웹소켓 보다는 훨 가볍고 좋아보입니다.
