### ISSUE TITLE
[공통] Springboot grafana, prometheus 설정

### ISSUE THREAD

**Issue by jojaeng2** [jojaeng2/2joryu#30]
# 목적
Springboot모니터링 시스템을 도입합니다. (일단 WAS만)

# 세부 구현 내용
- [ ] Prometheus - Spring 연동
- [ ] Grafana - Prometheus 연동

# 특이사항
WAS가 여러대일 경우 어떻게 할지 고민이 필요함.

**Comment by gusah009** [comment]
@jojaeng2 제가 도입해놓겠습니당
