### ISSUE TITLE
[공통] [로그] 로깅용 annotation 구현

### ISSUE THREAD

**Issue by jojaeng2** [jojaeng2/2joryu#33]
# 목적
KotlinLogging.logger {}를 통해 로그를 남기는 기존 방식이 아닌, annotation를 통해 남길 수 있도록 개선합니다.

# 세부 구현 내용

- [ ] 로깅 annotation 개발

# 특이사항
없음.

**Comment by jojaeng2** [comment]
@gusah009 @hyun98 
해당 issue close하겠습니다.

사유 : 
Custom annotation을 선언한다고 해서 Logger라는 필드를 생성할 수는 없음. 
annotation에는 단순 field(string, integer) 같은값만 넣을 수 있고 구체적 class를 선언 할 수 없음. 
구현하려면, 컴파일 단계까지 내려가서 구현을 해야하고, 이건 그냥 프레임 워크를 만드는 과정이 되어버림. (무겁고 성능 이슈가 어디서 생길지 예측 못함) 직접 custom annotation을 사용하는 경우는 Bean config 같은 파일들을 import해야 하는 경우, 다른 annotation을 조합하는 경우가 더 올바르다고 보임. 

결론 : 
1. 상속이나 전역 메서드를 만드는 방법
2. 매번 KLogger object를 생성하는 방법 (실제로 @Slf4j를 사용한 것과 같은 케이스)

**Comment by jojaeng2** [comment]
@gusah009 @hyun98 아니다 좀 더 해볼게용 class 참조할 수 있다고 해서

**Comment by gusah009** [comment]
그냥 제 추측인데 어노테이션 로거가 없는게 코틀린에서 롬복 못쓰는거랑 비슷한 맥락 아닐까요?

코틀린 컴파일 시점이랑 롬복 어노테이션에서 코드 만들어주는 시점이랑 엇갈려서 문제가 발생하는걸로 아는데, 롬복이 아니라 커스텀 어노테이션도 컴파일순서때매 같은 문제가 발생하지 않을까 싶네요...

저는 개인적으로 필드에 로거를 명시해주는것도 좋아보여서 어노테이션 로거가 굳이 필요한가 싶긴합니다 (소신발언)

**Comment by jojaeng2** [comment]
@gusah009 
ㅇㅇ 맞음 lombok을 사용하지 못하는 이유가 
1. kotlin이 먼저 compile 됨 -> lombok은 java라 후순위로 컴파일 됨
2. lombok이 컴파일 될때 이미 kotlin이 컴파일 끝나서 kotlin code에 java 코드가 들어가지 못함.

그래서 지금 시도 하는거는 reflection 사용해서 kotlin annotation에 static field로 logger를 명시하는 방법임
근데 kotlin에서 reflection 설정하는게 좀 많이 빡세서 정신 못차리는 상황.. 내부적으로 지원안해서 별도 라이브러리 의존성 받아서 시도하고 있는데, 자료가 너무 없음. 
그냥 포기하고 필드로 가죵..

**Comment by jojaeng2** [comment]
그리고 @Slf4j 뜯어보면, 지금 저희가 하는 방식이랑 똑같습니다. -> 성능 및 리소스 차이 존재하지 않음

**Comment by gusah009** [comment]
또 하나 배워갑니다 👍👍

**Comment by jojaeng2** [comment]
포기!
