### ISSUE TITLE
[채팅] Redis 연동 및 채팅 서비스 개발

### ISSUE THREAD

**Issue by hyun98** [jojaeng2/2joryu#8]
# 목적

1. 빠른 채팅 서비스를 위한 데이터 저장소 필요 - 속도
2. Scale Out 이 가능해야 함 - 확장성

채팅 메시지 데이터 저장소로 사용할 Redis를 연동한다.

# 세부 구현 내용

- [ ] Redis Pub/Sub 기능 개발
- [ ] 채팅방 별 메시지 전송 기능 개발

# 특이사항
- Redis 는 메시지 손실이 있을 수 있는 저장소이므로 추후 Replication 을 적용하고, 주기적으로 DB 백업을 담당하는 Batch 서버를 개발해 메시지 유실 가능성을 최소화한다

**Comment by jojaeng2** [comment]
Redis Stream을 쓰면 pub/sub에서 발생하는 메시지 유실 문제를 해결할 수 있습니다

**Comment by gusah009** [comment]
https://engineering.linecorp.com/ko/blog/how-line-messaging-servers-prepare-for-new-year-traffic

line은 redis를 주저장소로 쓰고 있다고 하네요

**Comment by jojaeng2** [comment]
저도 저거 보긴 했는데, redis에 다 담을 수는 없으니깐 최근 로그는 redis에 담고, batch 돌려서 mysql에 채팅 메시지 저장하는 방식을 사용하기로 이야기 했어요 메시지 읽을때 캐싱도 하구요 더 좋은 방법이 있을런지?

**Comment by gusah009** [comment]
@jojaeng2 @hyun98 

주저장소를 MySQL로 잡을거면 기본적인 redis 캐시 구조를 사용하면 안되나요? 

스프링 -> redis(캐시) -> MySQL(주저장소)

저장시 : DB에 저장이 성공하면 캐시에도 set
읽기시: redis에서 get 시도. 실패시 DB에 select 후 redis에 set

배치로 돌리면 배치에 문제가 생길 경우 메시지 유실 가능성이 있을 것 같아서...

**Comment by jojaeng2** [comment]
@gusah009 
흠.. 그러네요.. 그 문제가 생길 수도 있긴 하네요.
다만 batch를 적용하면 얻을 수 있는 이점도 좀 명확한거 같은데, 채팅 로그 저장할때마다 발생하는 DB I/O 시간을 줄일 수 있을 것 같긴해요
